version: '3'

services:
  postgresdb:
    image: postgres:14.2
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasklistdb
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - postgresdb
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:5432/tasklistdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile 
    depends_on:
      - backend
    ports:
      - "127.0.0.1:5173:5173"
  